### ISSUE TITLE
Errore nei link della puntata 27

### ISSUE THREAD

**Issue by Kurosama** [geekcookies/geekcookies.github.io#2]
Nella puntata 27 i link con caratteri "speciali" hanno qualche problema.

Esempio:
` https://play.google.com/store/apps/details?id%3Dcom.ratana.sunsurveyor`
non vengo mandato al link codificato corretto.
` https://play.google.com/store/apps/details?id=com.ratana.sunsurveyor`

Questo problema esiste solo in questa puntata perché, ad esempio, nella puntata 26 il link a Wikipedia funziona correttamente?!?!

**Comment by kidpixo** [comment]
Grazie mille! 

Effettivamente dall'ultima ho cambiato computer e gli script che uso per "tirare giú la scaletta da Google Doc in html > convertire in Markdown > strippare i tracker che Google incorpora in tutti i link e lo stile" non li avevo ancora testati.

In particolare i caratteri speciali delle URI vengono tradotti nelle HTML entities equivalenti: non so dove esattamente ma indagheró.

Grazie ancora!
